name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest "pdfminer.six>=20231228" "rich>=13.0.0" "typing-extensions>=4.0.0; python_version<'3.10'"
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
